name: fibo

on:
  workflow_dispatch:
  push :
    tags:
      - v1.**
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            yebigun/FibCalc
            ghcr.io/yebigun/FibCalc
          tags: |
            type=semver,pattern={{version}}  

      #Skonfigurowanie dockera + buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@master

      #Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      #Konfiguracja cachowania
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      #Logowanie do Dockerhuba
      - name: Login to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      #Logowanie do GHCR
      - name: Login to Github Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}
 
      #Zbudowanie i wypchniecie obrazu na Dockerhuba
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,src=docker.io/yebigun/buildcache
          cache-to: type=registry,dest=docker.io/yebigun/buildcache
          platforms: linux/arm64/v8,linux/amd64 
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{steps.meta.outputs.tags }}
          labels: ${{steps.meta.outputs.labels }}
      
      #Przenies cache'a
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
